# This is meant to be used with ./docker-compose.yml in production
services:
  storage:
    volumes:
      - ../../../supabase/volumes/storage:/var/lib/storage

  db:
    volumes:
      - ../../../supabase/volumes/db/data:/var/lib/postgresql/data
      - ./supabase/volumes/db/init:/docker-entrypoint-initdb.d
