# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root package.json
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      # Use Eastern Standard Time (UTC -05:00)
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
    # Disable automatic rebasing
    rebase-strategy: 'disabled'

  # Next Front-End package.json
  - package-ecosystem: 'npm'
    directory: '/src/web'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '04:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: nextjs'
    rebase-strategy: 'disabled'

  # Auto-deployment Server package.json
  - package-ecosystem: 'npm'
    directory: '/tools/autodeployment'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '06:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: autodeployment'
    rebase-strategy: 'disabled'

  # Auth Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/auth'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Feed-Discovery Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/feed-discovery'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '17:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Image Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/image'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '09:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Parser Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/parser'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '17:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Posts Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/posts'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '09:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Search Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/search'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '17:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Status Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/status'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '09:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Users Service package.json
  - package-ecosystem: 'npm'
    directory: '/src/api/users'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '17:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: microservices'
    rebase-strategy: 'disabled'

  # Root Dockerfile
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '06:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Auth Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/auth'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '13:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Feed Discovery Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/feed-discovery'
    schedule:
      interval: 'weekly'
      day: 'tuesday'
      time: '13:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Image Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/image'
    schedule:
      interval: 'weekly'
      day: 'wednesday'
      time: '13:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Parser Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/parser'
    schedule:
      interval: 'weekly'
      day: 'thursday'
      time: '13:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Posts Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/posts'
    schedule:
      interval: 'weekly'
      day: 'friday'
      time: '13:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Search Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/search'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '09:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Status Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/status'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '13:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # Users Service Dockerfile
  - package-ecosystem: 'docker'
    directory: '/src/api/users'
    schedule:
      interval: 'weekly'
      day: 'saturday'
      time: '17:00'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: docker'
    rebase-strategy: 'disabled'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
      timezone: 'America/Toronto'
    open-pull-requests-limit: 1
    commit-message:
      prefix: 'chore: '
    reviewers:
      - 'Seneca-CDOT/telescope-maintainers'
    labels:
      - 'dependencies'
      - 'area: CI/CD'
    rebase-strategy: 'disabled'
