# Learn more about this file at https://www.gitpod.io/docs/references/gitpod-yml
tasks:
  - name: Service Server
    # Get Web API urls for use in Next build
    # Copy env.development and replace localhost wit gitpod urls
    before: |
      eval $(gp env -e API_URL=$(gp url 3000))
      eval $(gp env -e WEB_URL=$(gp url 8000))
      eval $(gp env -e API_HOST=$(gp url 8443))

      sed -r \
          -e  "s@(.+=)http://localhost:3000(/.*)*@\1$API_URL\2@g" \
          -e  "s@(.+=)http://localhost:8000(/.*)*@\1$WEB_URL\2@g" \
          -e  "s@(.+=)http://localhost(/.*)*@\1$API_HOST\2@g" \
          -e  "s@development\.yml@gitpod\.yml@" \
          config/env.development > .env
    init: |
      npm install
      docker-compose --env-file .env build
    # GitPod workspace urls are not stable, we have to look up urls and build nginx again
    command: |
      docker-compose --env-file config/env.gitpod up -d --no-dep nginx
      docker-compose --env-file .env up -d
      gp await-port 9200 && npm run start

  - name: Terminal
    openMode: tab-after

ports:
  # NextJS frontend
  - port: 8000
    visibility: public
    onOpen: open-preview
  # Web API
  - port: 3000
    visibility: public
    onOpen: ignore

github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: false

# Install recommended extension
vscode:
  extensions:
    - editorconfig.editorconfig
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - streetsidesoftware.code-spell-checker
