# pnpm workspace definition: https://pnpm.io/pnpm-workspace_yaml
packages:
  # docusaurus web app
  - 'src/web/docusaurus'
  # web front-end
  - 'src/web/app'
  # microservices
  - 'src/api/*'
  # satellite
  - 'src/satellite'
  # autodeployment
  - 'tools/*'
