# pnpm workspace definition: https://pnpm.io/pnpm-workspace_yaml
packages:
  # docusaurus web app
  - 'src/docs'
  # web front-end
  - 'src/web'
  # microservices
  - 'src/api/*'
  # autodeployment
  - 'tools/*'
