# pnpm workspace definition: https://pnpm.io/pnpm-workspace_yaml
# Do not list packages that you want to download and use from npm registry
packages:
  # docusaurus web app
  - 'src/docs'
  # web front-end
  - 'src/web'
  # microservices
  - 'src/api/*'
  # autodeployment
  - 'tools/*'
