# pnpm workspace definition: https://pnpm.io/pnpm-workspace_yaml
packages:
  # web front-end
  - 'src/web/*'
  # microservices
  - 'src/api/*'
  # satellite
  - 'src/satellite'
  # github-url-parser
  - 'src/github-url-parser'
  # autodeployment
  - 'tools/*'
  # Prisma
  - 'src/db'
