#!/bin/sh

TIMESTAMP="$(date +%Y-%m-%d-%H%M%S)"

pg_dump --format=custom \
	--host=$PG_HOST_NAME \
	--port=$PG_HOST_PORT \
	--dbname=$PG_DB_NAME \
	--username=$PG_USER_NAME \
	--password=$PG_USER_PASSWORD > "/var/opt/pg_dumps/$TIMESTAMP.dump"
