version: '3'

services:
  # API Gateway
  traefik:
    image: traefik:v2.4
    container_name: 'traefik'
    restart: unless-stopped
    command:
      - '--log.level=DEBUG'
      - '--api.insecure=true'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=true'
      - '--entrypoints.web.address=:80'
    ports:
      - '80:80'
      - '8080:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  # Micro Services
  image:
    container_name: 'image'
    restart: unless-stopped
    build:
      context: ./image
      dockerfile: Dockerfile
    environment:
      - IMAGE_PORT=4444
      - SERVICE_NAME=image
    depends_on:
      traefik:
        condition: service_started
    ports:
      - '4444'
    labels:
      # Traefik routing
      - 'traefik.http.routers.image.rule=Host(`image.docker.localhost`)'
      # Enable gzip compression
      - 'traefik.http.routers.image.middlewares=test-compress'
      - 'traefik.http.middlewares.test-compress.compress=true'
