################################################################################
# Production docker-compose.yml, not meant for local development
#
# This docker-compose file is meant to be used to override settings in the
# src/api/docker-compose.yml base specification:
#
# $ docker-compose -f docker-compose.yml -f production.yml up -d
#
# See https://docs.docker.com/compose/production/
################################################################################
version: '3'

services:
  # API Gateway
  traefik:
    restart: unless-stopped
    command:
      - '--api.insecure=false'
      - '--providers.docker=true'
      - '--providers.docker.exposedbydefault=false'
      - '--entrypoints.web.address=:80'
      # TODO: https/ssl setup...
    ports:
      - '80:80'
      - '8080:8080'
    labels:
      - 'traefik.enable=true'
      # GZip compression middleware: gzip_compress
      - 'traefik.http.middlewares.gzip_compress.compress=true'

  # image service
  image:
    restart: unless-stopped
    depends_on:
      - apm
      - traefik
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_APM_SERVICE_NAME=image
      - ELASTIC_APM_SERVER_URL=http://apm:8200
    labels:
      # Add gzip compression too
      - 'traefik.http.routers.image.middlewares=gzip_compress,strip_image_prefix'
      # ELK Logging
      - 'co.elastic.logs/json.keys_under_root: true'
      - 'co.elastic.logs/json.overwrite_keys: true'
      - 'co.elastic.logs/json.add_error_key: true'
      - 'co.elastic.logs/json.expand_keys: true'
      - 'co.elastic.logs/json.message_key: message'

  # auth service
  auth:
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTIC_APM_SERVICE_NAME=auth
      - ELASTIC_APM_SERVER_URL=http://apm:8200
    depends_on:
      - apm
      - traefik
    labels:
      # Add gzip compression too
      - 'traefik.http.routers.auth.middlewares=gzip_compress,strip_auth_prefix'
      # ELK Logging
      - 'co.elastic.logs/json.keys_under_root: true'
      - 'co.elastic.logs/json.overwrite_keys: true'
      - 'co.elastic.logs/json.add_error_key: true'
      - 'co.elastic.logs/json.expand_keys: true'
      - 'co.elastic.logs/json.message_key: message'

  # ELK Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    container_name: 'elasticsearch'
    restart: unless-stopped
    environment:
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - discovery.type=single-node
    # See the following:
    # - https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-docker.html,
    # - https://github.com/deviantony/docker-elk/issues/243
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - '9200'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    container_name: 'kibana'
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    volumes:
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - '5601'

  # System Metrics Logging
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.9.3
    container_name: 'metricbeat'
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  # Logging
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.2
    container_name: 'filebeat'
    restart: unless-stopped
    # Need root for access to Docker daemon at unix:///var/run/docker.sock
    user: root
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_HOST=http://kibana:5601
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:rw
      # Allows us to report on docker from the hosts information.
      - /var/run/docker.sock:/var/run/docker.sock
      # Allows us to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro
    command: filebeat -e -strict.perms=false
    depends_on:
      - elasticsearch

  # Application Performance Monitoring
  apm:
    image: docker.elastic.co/apm/apm-server:7.10.2
    container_name: 'apm'
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_HOST=http://kibana:5601
    ports:
      - '8200'
    depends_on:
      - elasticsearch

volumes:
  elasticsearch:
