// Sanitize HTML and prevent XSS attacks
// <img src=x onerror=alert(1)> becomes <img src="x">

const sanitizeHtml = require('dompurify');
module.exports = function (dirty) {
  var e = sanitizeHtml.sanitize(dirty, {
    ALLOWED_TAGS: [
      'a',
      'b',
      'blockquote',
      'br',
      'caption',
      'code',
      'del',
      'div',
      'em',
      'figure',
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      'hr',
      'i',
      'iframe',
      'img',
      'li',
      'ol',
      'p',
      'pre',
      'strike',
      'strong',
      'table',
      'tbody',
      'td',
      'th',
      'thread',
      'tr',
      'ul',
      'MDXPageBase',
    ],
    ADD_TAGS: ['iframe', 'MDXPageBase'],
    ADD_ATTR: ['src'],
    FORBID_TAGS: ['style', 'class', 'cellspacing', 'align', 'cellpadding'],
    FORBID_ATTR: [
      'style',
      'class',
      'width',
      'height',
      'cellspacing',
      'align',
      'cellpadding',
      'border',
      'alt',
    ],
    RETURN_DOM: true,
  });
  return e.getElementsByTagName('body');
};
