name: Autodeployment Webhook

on:
  workflow_call:
    inputs:
      deploy_tag:
        description: 'The deploy tag to use, one of `staging` or `production`'
        required: true
        type: string
      webhook_url:
        description: 'The webhook URL to use'
        required: true
        type: string
    secrets:
      webhook_token:
        description: 'The webhook secret token to use'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke autodeployment webhook for staging
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_type: 'json-extended'
          webhook_url: ${{ inputs.webhook_url }}
          webhook_secret: ${{ secrets.webhook_token }}
          data: '{ "deploy_tag": "${{ inputs.deploy_tag }}" }'
