name: docs-ci

on:
  pull_request:
    branches:
      - master
    paths:
      - 'src/docs/**'
  push:
    branches:
      - master
    paths:
      - 'src/docs/**'

jobs:
  # Confirm that prettier was run on the changes
  prettier:
    uses: Seneca-CDOT/telescope/.github/workflows/prettier-ci.yml@master

  # Make sure eslint passes
  eslint:
    uses: Seneca-CDOT/telescope/.github/workflows/eslint-ci.yml@master
