name: e2e Tests Workflow

on:
  workflow_call:

jobs:
  e2e:
    name: End-To-End Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    env:
      # Whichever Docker containers are needed to pass e2e tests, define them here
      DOCKER_CONTAINERS: 'sso feed-discovery auth login kong rest meta elasticsearch redis posts traefik'
      # Postgres database connection string to run db migration
      DATABASE_URL: 'postgresql://postgres:your-super-secret-and-long-postgres-password@localhost/postgres'

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - uses: pnpm/action-setup@v2.2.1

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - uses: docker/setup-buildx-action@v1

      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright dependencies
        run: sudo apt install -y libglib2.0-0 libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libatspi2.0-0 libxcomposite1 libxdamage1 libxfixes3 libxrandr2 libgbm1 libxkbcommon0 libpango-1.0-0 libcairo2 libasound2
      - name: This is the dumbest thing I've ever seen
        run: sudo npx playwright install --with-deps
      # Pull, build, and run containers, then start e2e tests
      - name: Pull/Build Docker Containers Necessary for Running E2E Tests
        run: docker compose --env-file ./config/env.development up -d ${{ env.DOCKER_CONTAINERS }}
      - name: Wait for Postgres and Login containers to become fully ready
        run: pnpx -y wait-on -t 60000 tcp:5432 http://localhost:8081/simplesaml
      - name: Apply database migrations
        run: pnpm db:migrate
      - run: pnpm jest:e2e
