name: Unit Tests Workflow

on:
  workflow_call:
    secrets:
      turbo_server_token:
        description: 'The Turborepo local server token'
        required: true

jobs:
  unit:
    name: Unit Tests
    runs-on: ${{matrix.os}}
    env:
      SERVER_TOKEN: ${{ secrets.turbo_server_token }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Turborepo local server
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ github.token }}
          server-token: ${{ env.SERVER_TOKEN }}

      - name: Install dependencies and run tests with default env
        run: |
          pnpm install
          pnpm turbo run test --api="http://127.0.0.1:9080" --token="${{ env.SERVER_TOKEN }}"
