name: Unit Tests Workflow

on:
  workflow_call:
    secrets:
      github-token:
        description: 'The GitHub authentication token'
        required: true
      turborepo-token:
        description: 'The Turborepo local server token'
        required: true

jobs:
  unit:
    name: Unit Tests
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Turborepo local server
        uses: felixmosh/turborepo-gh-artifacts@v1
        with:
          repo-token: ${{ secrets.github-token }}
          server-token: ${{ secrets.turborepo-token }}

      - name: Install dependencies and run tests with default env
        run: |
          pnpm install
          pnpm turbo run test --api="http://127.0.0.1:9080" --token="${{ secrets.server-token }}"
